services:
  api:
    build:
      context: docker/laravel
      args:
        - UID=1000
        - GID=1000
    volumes:
      - "./api:/app"
    ports:
      - "3001:3001"
    depends_on:
      - database
      - cache
  database:
    image: mysql:8
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=messenger
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "./data/mysql:/var/lib/mysql"
  cache:
    image: redis:7
    volumes:
      - "./data/redis:/data"
